language: ruby
script: bundle exec rspec
before_install:
  - gem install bundler
rvm:
  - 2.2.0
  - 2.3.0
  - 2.4.0
env:
  - ACTIVE_RECORD_VERSION='~> 4.2.0'
  - ACTIVE_RECORD_VERSION='~> 5.0.0'
  - ACTIVE_RECORD_VERSION='~> 5.1.0'
matrix:
  exclude:
    - rvm: 2.2.0
      env: ACTIVE_RECORD_VERSION='~> 5.0.0'
    - rvm: 2.2.0
      env: ACTIVE_RECORD_VERSION='~> 5.1.0'
